name: actions
on:
  push:
    branches:
      - master
    paths:
      - containers/**
      - .github/workflows/actions.yml
      - "*.sh"
  pull_request:
    branches:
      - master
    paths:
      - containers/**
      - .github/workflows/actions.yml
      - "*.sh"
jobs:
  qemu-user-static:
    runs-on: ubuntu-latest
    env:
      VERSION: 10.0.2
      ORIGIN_VERSION: 10.0.2+ds-2
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set variables
        run: |
          echo "DOCKER_REPO=docker.io/$GITHUB_REPOSITORY" >> $GITHUB_ENV
          echo "GHCR_REPO=ghcr.io/$GITHUB_REPOSITORY" >> $GITHUB_ENV
      - name: Build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          ./run.sh -t "${{ env.VERSION }}" -d "${{ env.DOCKER_REPO }}" -x linux/amd64
      - name: Test
        run: ./test.sh -d "${{ env.DOCKER_REPO }}"
      - name: Push multi-arch
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          ./run.sh -t "${{ env.VERSION }}" -d "${{ env.DOCKER_REPO }}" -p
          ./run.sh -t "${{ env.VERSION }}" -d "${{ env.GHCR_REPO }}" -p
